generator:
  datasource:
    url: jdbc:mysql://localhost:3306/shine_security?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true
    username: root
    password: 123456
  # 包配置
  package-config:
    modal-name: security
    base-package: com.shine
  # 生成配置
  generator:
    database: shine_security
    table-name:
      - oauth_authorization_code
#      - user
#      - role
#      - oauth_authorization_code
#      - oauth_client_scope
    table-prefix: oauth_
    # 需要生成的
    code:
      - entity
      - enum
      - info
      - page_request
      - create_request
      - update_request
      - mapper
      - mapper_xml
      - service
      - service_impl
      - controller
    methods:
      - page
      - get
      - delete



spring:
  datasource:
    url: ${generator.datasource.url}
    username: ${generator.datasource.username}
    password: ${generator.datasource.password}