xxl-job:
  admin:
    # 调度中心服务部署的地址
    addresses: http://192.168.128.1:28080/xxl-job-admin
  # 执行器通讯TOKEN,要和调度中心服务部署配置的accessToken一致，要不然无法连接注册
  accessToken: shine
  executor:
    # 执行器AppName
    appName: xxl-job-test
    # 执行器注册 [选填]
    address:
    ip:
    #执行器端口号: 小于等于0则自动获取 默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口；
    port: 0
    # 执行器运行日志文件存储磁盘路径 [选填] 需要对该路径拥有读写权限；为空则使用默认路径；
    logPath: J:/cloud-components/xxl-job/logs/handle
    # 执行器日志文件保存天数 [选填] 过期日志自动清理, 限制值大于等于3时生效  否则, 如-1, 关闭自动清理功能
    logRetentionDays: 15

