generator:
  datasource:
    url: jdbc:mysql://localhost:3306/hh_user?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true
    username: root
    password: 123456
spring:
  datasource:
    url: ${generator.datasource.url}
    username: ${generator.datasource.username}
    password: ${generator.datasource.password}