generator:
  datasource:
    url: jdbc:mysql://localhost:3306/hh_user?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true
    username: root
    password: 123456
  # 包配置
  package-config:
    modal-name: user
    base-package: com.hh
  # 生成配置
  generator:
    database: hh_user
    table-name: user
    table-prefix: ""
    # 需要生成的
    code:
      - entity
      - info



spring:
  datasource:
    url: ${generator.datasource.url}
    username: ${generator.datasource.username}
    password: ${generator.datasource.password}