spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: shine
    password: shine
    virtual-host: /shine
    publisher-returns: true
    publisher-confirm-type: correlated # 发送确认
    listener:
      simple:
        acknowledge-mode: manual # 手动应答
        prefetch: 1 # 每次推送一条
