server:
  port: 8888

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    dynamic:
      primary: auth
      strict: false
      datasource:
        auth:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/hh_auth?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true
          username: root
          password: 123456

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.hh.user.entity
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名：默认开启，【二选一】
    cache-enabled: true # 开启二级缓存，默认开启
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  api-docs:
    enabled: ${swagger.enable}

swagger:
  enable: true
  title: 安全服务
  description: 安全服务Swagger接口文档
  version: 1.0.0
  documentation-description: 用户服务Swagger接口文档
  url: /

nacos:
  server-addr: 127.0.0.1:8848
  username: nacos
  password: nacos
  namespace: 7a315776-c8ed-4a70-be9c-2d60debde2e8
  group: DEFAULT_GROUP
spring:
  application:
    name: security-service
  cloud:
    nacos:
      discovery:
        server-addr: ${nacos.server-addr}
        username: ${nacos.username}
        password: ${nacos.password}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
      config:
        server-addr: ${nacos.server-addr}
        username: ${nacos.username}
        password: ${nacos.password}
        namespace: ${nacos.namespace}
        group: ${nacos.group}
        prefix: ${spring.application.name}
        file-extension: yml
        shared-configs[0]:
          data-id: redis.yml
          group: DEFAULT_GROUP
          refresh: true
        shared-configs[1]:
          data-id: cos.yml
          group: DEFAULT_GROUP
          refresh: true
        shared-configs[2]:
          data-id: rabbit.yml
          group: DEFAULT_GROUP
          refresh: true
